version: '3.6'
services:
  website:
    build: 
      context: .
    container_name: lauva_website
    restart: unless-stopped
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      TOTP_SECRET: ${TOTP_SECRET}
      CSRF_SECRET: ${CSRF_SECRET}
    networks:
      - proxy
      
networks:
  proxy:
    external: true